name: zard
description: Zard is a schema validation and transformation library for Dart, inspired by the popular Zod library for JavaScript.
version: 0.0.18
homepage: https://github.com/evandersondev/zard
repository: https://github.com/evandersondev/zard

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
